language: python
sudo: false

matrix:
  include:
    - python: "2.7"
      env: DEPS="numpy=1.8 scipy=0.13.3 matplotlib=1.3 pandas=0.13 scikit-image=0.9"
    - python: "3.5"
      env: DEPS="numpy scipy matplotlib pandas scikit-image"

install:
  - conda update --yes conda
  - conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - python setup.py install

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script: nosetests --nologcapture -a '!slow'
